# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        post_edit:
            toolbar: post_edit_toolbar
            entities: false
    toolbars:
        configs:
            post_edit_toolbar: [ 
                '@standard.clipboard',
                '@standard.editing',
                '@standard.links',
                '@standard.insert',
                '@standard.tools',
                '@standard.document',
                '/',
                '@standard.basic_styles',
                '@full.colors',
                '@full.styles',
                '@full.paragraph'
            ]
        items:
            standard.colors: [ "TextColor", "BGColor" ]
            