framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(EMAIL_NOTIF_SENDER)%'
when@test:
    framework:
        mailer:
            dsn: 'null://null'
            envelope:
                recipients: ['test@test.com']