framework:
    workflows:
        timeslot:
            type: 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Timeslot
            initial_marking: draft
            places:
                - draft
                - open
                - validated
                - closed
            transitions:
                to_open:
                    from: draft
                    to: open
                to_validated:
                    from: open
                    to:   validated
                to_closed:
                    from: open
                    to: closed
                to_closed_open:
                    from: closed
                    to: open

