services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Functional\:
        resource: '../tests/Functional/*'
        exclude: '../tests/Functional/{Page}'
    
    App\Tests\Functional\Page\:
        resource: '../tests/Functional/Page/*'
        parent: 'FriendsOfBehat\PageObjectExtension\Page\SymfonyPage'
        autoconfigure: false
        public: false
        autowire: true
    
    FriendsOfBehat\PageObjectExtension\Page\Page:
        abstract: true
        autoconfigure: false
        public: false
        autowire: true
        arguments:
            - '@behat.mink.default_session'
            - '@behat.mink.parameters'
    
    FriendsOfBehat\PageObjectExtension\Page\SymfonyPage:
        abstract: true
        autoconfigure: false
        public: false
        autowire: true
        parent: 'FriendsOfBehat\PageObjectExtension\Page\Page'
        arguments:
            - '@router'