name: Pipeline-CD to Production environment
on:
  push:
    branches: [ env-prod ]
jobs:
  cd:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy Over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ENV_PROD_SSH_HOST }}
          username: ${{ secrets.ENV_PROD_SSH_USER }}
          key: ${{ secrets.ENV_PROD_SSH_PRIVATE_KEY }}
          port: ${{ secrets.ENV_PROD_SSH_PORT }}
          script: |
            ls
            # cd ${{ secrets.ENV_PROD_DIST_PROJECT_DIR }}
            # git pull
            # composer2 install
            # php bin/console doctrine:migrations:migrate

      # - name: copy yarn build via ssh password
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.ENV_PROD_SSH_HOST }}
      #     username: ${{ secrets.ENV_PROD_SSH_USER }}
      #     key: ${{ secrets.ENV_PROD_SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.ENV_PROD_SSH_PORT }}
      #     source: "./public/build"
      #     target: "${{ secrets.ENV_PROD_DIST_PROJECT_DIR }}/public/build"