name: Pipeline-CD to Production environment
on: workflow_dispatch
jobs:
  cd:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2

      - name: Yarn install
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          #registry-url: npm.fontawesome.com
      - run: yarn install
          #env:
          #NODE_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Yarn build
        run: yarn run encore production
      
      - name: Deploy Over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ENV_PROD_SSH_HOST }}
          username: ${{ secrets.ENV_PROD_SSH_USER }}
          key: ${{ secrets.ENV_PROD_SSH_PRIVATE_KEY }}
          port: ${{ secrets.ENV_PROD_SSH_PORT }}
          script_stop: true
          script: |
            cd ${{ secrets.ENV_PROD_DIST_PROJECT_DIR }}
            source ~/.profile
            git checkout ${{ github.ref_name }}
            git pull
            composer2 install
            php bin/console --no-interaction doctrine:migrations:migrate 

      - name: copy yarn build via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ENV_PROD_SSH_HOST }}
          username: ${{ secrets.ENV_PROD_SSH_USER }}
          key: ${{ secrets.ENV_PROD_SSH_PRIVATE_KEY }}
          port: ${{ secrets.ENV_PROD_SSH_PORT }}
          source: "public/build/*"
          target: "${{ secrets.ENV_PROD_DIST_PROJECT_DIR }}/public/build"
          strip_components: 2
          rm: true
