name: Pipeline-CD
on:
  push:
    branches: [ test ]
jobs:
  cd:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy Over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SSH_HOST }}
          username: ${{ secrets.TEST_SSH_USER }}
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: ${{ secrets.TEST_SSH_PORT }}
          script: |
            cd ${{ secrets.TEST_DIST_PROJECT_DIR }}
            git pull
            composer2 install
            php bin/console doctrine:migrations:migrate
