name: Pipeline-CI
on:
  push:
    branches: [ main ]
  workflow_dispatch
jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: false
    services:
      mariadb:
        image: 'mariadb:latest'
        env: 
          MARIADB_USER: kreno
          MARIADB_PASSWORD: kreno
          MARIADB_ROOT_PASSWORD: kreno
          MARIADB_DATABASE: kreno
        ports:
          - 3306:3306
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
          
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
      
      - name: "Composer install"
        run: composer install --no-interaction --no-progress
        
      # Install Symfony CLI
      - name: Symfony CLI
        run: |
            echo 'deb [trusted=yes] https://repo.symfony.com/apt/ /' | sudo tee /etc/apt/sources.list.d/symfony-cli.list
            sudo apt update
            sudo apt install symfony-cli
        
      # Check vulnerabilities
      - name: Symfony Check Vulnerabilities
        run: symfony check:security

      # PHP CS FIXER
      - name: PHP-CS-Fixer
        run: |
          composer require friendsofphp/php-cs-fixer
          ./vendor/bin/php-cs-fixer fix src --dry-run

      # PHP STAN
      - name: PHP Stan
        run: |
          ./vendor/bin/simple-phpunit install
          composer require phpstan/phpstan
          composer require phpstan/extension-installer
          composer config --no-plugins allow-plugins.phpstan/extension-installer true
          composer require phpstan/phpstan-symfony
          ./vendor/bin/phpstan analyse src --memory-limit 1G
          
      - name: Lint YAML files
        run: ./bin/console lint:yaml config --parse-tags

      - name: Lint Twig templates
        run: ./bin/console lint:twig templates --env=test

      - name: Lint Parameters and Services
        run: ./bin/console lint:container --no-debug

      - name: Lint Doctrine entities
        run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

      - name: PHP Unit
        run: ./bin/phpunit
